[build]
  functions = "netlify/functions"
  publish = "./"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

  # Redirect friendly paths without file extensions to the correct HTML files
[[redirects]]
  from = "/product"
  to = "/product.html"
  status = 200
  force = true

[[redirects]]
  from = "/products"
  to = "/products.html"
  status = 200
  force = true

[[redirects]]
  from = "/categories"
  to = "/categories.html"
  status = 200
  force = true

[[redirects]]
  from = "/cart"
  to = "/cart.html"
  status = 200
  force = true

[[redirects]]
  from = "/cancel"
  to = "/cancel.html"
  status = 200
  force = true

[[redirects]]
  from = "/thankyou"
  to = "/thankyou.html"
  status = 200
  force = true

## Redirect voor verzendpagina verwijderd omdat verzendinformatie nu onderdeel is van het afrekenproces
# [[redirects]]
#   from = "/shipping"
#   to = "/shipping.html"
#   status = 200
#   force = true