
/*
 * Dynamische inventaris voor geüploade producten.
 *
 * Dit bestand definieert een array met objecten voor alle foto's die
 * door de gebruiker zijn aangeleverd (de zogeheten "uploads"). Elk
 * object bevat een titel, de afbeeldingslocatie, een categorie,
 * een richtprijs en metadata. Door deze array als globale variabele
 * beschikbaar te stellen (UPLOAD_ITEMS) kan main.js deze items
 * toevoegen aan de bestaande productinventaris wanneer de site wordt
 * geladen.
 */

const UPLOAD_ITEMS = [
  {"title": "Detective Pikachu (Nintendo 3DS)", "image": "images/uploads/upload-0001.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Detective Pikachu (Nintendo 3DS)", "image": "images/uploads/upload-0002.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Ultra Sun (Nintendo 3DS)", "image": "images/uploads/upload-0003.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Ultra Sun (Nintendo 3DS)", "image": "images/uploads/upload-0004.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Moon (Nintendo 3DS)", "image": "images/uploads/upload-0005.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Moon (Nintendo 3DS)", "image": "images/uploads/upload-0006.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Sun (Nintendo 3DS)", "image": "images/uploads/upload-0007.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Sun (Nintendo 3DS)", "image": "images/uploads/upload-0008.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon X (Nintendo 3DS)", "image": "images/uploads/upload-0009.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon X (Nintendo 3DS)", "image": "images/uploads/upload-0010.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Ultra Moon (Nintendo 3DS)", "image": "images/uploads/upload-0011.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Ultra Moon (Nintendo 3DS)", "image": "images/uploads/upload-0012.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Mystery Dungeon: Gates to Infinity (Nintendo 3DS)", "image": "images/uploads/upload-0013.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Mystery Dungeon: Gates to Infinity (Nintendo 3DS)", "image": "images/uploads/upload-0014.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Super Pokémon Rumble (Nintendo 3DS)", "image": "images/uploads/upload-0015.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Super Pokémon Rumble (Nintendo 3DS)", "image": "images/uploads/upload-0016.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Omega Ruby (Nintendo 3DS)", "image": "images/uploads/upload-0017.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Omega Ruby (Nintendo 3DS)", "image": "images/uploads/upload-0018.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Alpha Sapphire (Nintendo 3DS)", "image": "images/uploads/upload-0019.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Alpha Sapphire (Nintendo 3DS)", "image": "images/uploads/upload-0020.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Pokémon Alpha Sapphire (Nintendo 3DS)", "image": "images/uploads/upload-0021.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Pokémon Alpha Sapphire (Nintendo 3DS)", "image": "images/uploads/upload-0022.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Pokémon Omega Ruby (Nintendo 3DS)", "image": "images/uploads/upload-0023.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Pokémon Omega Ruby (Nintendo 3DS)", "image": "images/uploads/upload-0024.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Super Mario Odyssey (Nintendo Switch)", "image": "images/uploads/upload-0025.jpg", "category": "Nintendo Switch", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Super Mario Odyssey (Nintendo Switch)", "image": "images/uploads/upload-0026.jpg", "category": "Nintendo Switch", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Luigi's Mansion 3 (Nintendo Switch)", "image": "images/uploads/upload-0027.jpg", "category": "Nintendo Switch", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Luigi's Mansion 3 (Nintendo Switch)", "image": "images/uploads/upload-0028.jpg", "category": "Nintendo Switch", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "FIFA 20 Legacy Edition (Nintendo Switch)", "image": "images/uploads/upload-0029.jpg", "category": "Nintendo Switch", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "FIFA 20 Legacy Edition (Nintendo Switch)", "image": "images/uploads/upload-0030.jpg", "category": "Nintendo Switch", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Mario + Rabbids: Kingdom Battle (Nintendo Switch)", "image": "images/uploads/upload-0031.jpg", "category": "Nintendo Switch", "price": 20, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Mario + Rabbids: Kingdom Battle (Nintendo Switch)", "image": "images/uploads/upload-0032.jpg", "category": "Nintendo Switch", "price": 20, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Shining Pearl (Nintendo Switch)", "image": "images/uploads/upload-0033.jpg", "category": "Nintendo Switch", "price": 35, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Shining Pearl (Nintendo Switch)", "image": "images/uploads/upload-0034.jpg", "category": "Nintendo Switch", "price": 35, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "EA Sports FC 24 (Nintendo Switch)", "image": "images/uploads/upload-0035.jpg", "category": "Nintendo Switch", "price": 20, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "EA Sports FC 24 (Nintendo Switch)", "image": "images/uploads/upload-0036.jpg", "category": "Nintendo Switch", "price": 20, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Super Mario Party (Nintendo Switch)", "image": "images/uploads/upload-0037.jpg", "category": "Nintendo Switch", "price": 35, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Super Mario Party (Nintendo Switch)", "image": "images/uploads/upload-0038.jpg", "category": "Nintendo Switch", "price": 35, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "New Super Mario Bros. U Deluxe (Nintendo Switch)", "image": "images/uploads/upload-0039.jpg", "category": "Nintendo Switch", "price": 35, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "New Super Mario Bros. U Deluxe (Nintendo Switch)", "image": "images/uploads/upload-0040.jpg", "category": "Nintendo Switch", "price": 35, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Miitopia (Nintendo Switch)", "image": "images/uploads/upload-0041.jpg", "category": "Nintendo Switch", "price": 30, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Miitopia (Nintendo Switch)", "image": "images/uploads/upload-0042.jpg", "category": "Nintendo Switch", "price": 30, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Mario Party Superstars (Nintendo Switch)", "image": "images/uploads/upload-0043.jpg", "category": "Nintendo Switch", "price": 35, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Mario Party Superstars (Nintendo Switch)", "image": "images/uploads/upload-0044.jpg", "category": "Nintendo Switch", "price": 35, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Super Smash Bros. Ultimate (Nintendo Switch)", "image": "images/uploads/upload-0045.jpg", "category": "Nintendo Switch", "price": 35, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Super Smash Bros. Ultimate (Nintendo Switch)", "image": "images/uploads/upload-0046.jpg", "category": "Nintendo Switch", "price": 35, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Scarlet (Nintendo Switch)", "image": "images/uploads/upload-0047.jpg", "category": "Nintendo Switch", "price": 35, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Scarlet (Nintendo Switch)", "image": "images/uploads/upload-0048.jpg", "category": "Nintendo Switch", "price": 35, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Super Mario 3D World + Bowser's Fury (Nintendo Switch)", "image": "images/uploads/upload-0049.jpg", "category": "Nintendo Switch", "price": 35, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Super Mario 3D World + Bowser's Fury (Nintendo Switch)", "image": "images/uploads/upload-0050.jpg", "category": "Nintendo Switch", "price": 35, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Mario + Rabbids: Sparks of Hope (Nintendo Switch)", "image": "images/uploads/upload-0051.jpg", "category": "Nintendo Switch", "price": 25, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Mario + Rabbids: Sparks of Hope (Nintendo Switch)", "image": "images/uploads/upload-0052.jpg", "category": "Nintendo Switch", "price": 25, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Super Mario 3D All-Stars (Nintendo Switch)", "image": "images/uploads/upload-0053.jpg", "category": "Nintendo Switch", "price": 90, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Super Mario 3D All-Stars (Nintendo Switch)", "image": "images/uploads/upload-0054.jpg", "category": "Nintendo Switch", "price": 90, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Pokémon Ultra Moon (Nintendo 3DS)", "image": "images/uploads/upload-0055.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Pokémon Ultra Moon (Nintendo 3DS)", "image": "images/uploads/upload-0056.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Pokémon X (Nintendo 3DS)", "image": "images/uploads/upload-0057.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Pokémon X (Nintendo 3DS)", "image": "images/uploads/upload-0058.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Pokémon Sun (Nintendo 3DS)", "image": "images/uploads/upload-0059.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Pokémon Sun (Nintendo 3DS)", "image": "images/uploads/upload-0060.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Pokémon Moon (Nintendo 3DS)", "image": "images/uploads/upload-0061.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Pokémon Moon (Nintendo 3DS)", "image": "images/uploads/upload-0062.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Pokémon Ultra Sun (Nintendo 3DS)", "image": "images/uploads/upload-0063.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Pokémon Ultra Sun (Nintendo 3DS)", "image": "images/uploads/upload-0064.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Detective Pikachu (Nintendo 3DS)", "image": "images/uploads/upload-0065.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Detective Pikachu (Nintendo 3DS)", "image": "images/uploads/upload-0066.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Xenoblade Chronicles: Definitive Edition (Nintendo Switch)", "image": "images/uploads/upload-0067.jpg", "category": "Nintendo Switch", "price": 40, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Xenoblade Chronicles: Definitive Edition (Nintendo Switch)", "image": "images/uploads/upload-0068.jpg", "category": "Nintendo Switch", "price": 40, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Fire Emblem: Three Houses (Nintendo Switch)", "image": "images/uploads/upload-0069.jpg", "category": "Nintendo Switch", "price": 35, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Fire Emblem: Three Houses (Nintendo Switch)", "image": "images/uploads/upload-0070.jpg", "category": "Nintendo Switch", "price": 35, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Child of Light & Valiant Hearts: The Great War (Nintendo Switch)", "image": "images/uploads/upload-0071.jpg", "category": "Nintendo Switch", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Child of Light & Valiant Hearts: The Great War (Nintendo Switch)", "image": "images/uploads/upload-0072.jpg", "category": "Nintendo Switch", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Xenoblade Chronicles 2 (Nintendo Switch)", "image": "images/uploads/upload-0073.jpg", "category": "Nintendo Switch", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Xenoblade Chronicles 2 (Nintendo Switch)", "image": "images/uploads/upload-0074.jpg", "category": "Nintendo Switch", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "L.A. Noire (Nintendo Switch)", "image": "images/uploads/upload-0075.jpg", "category": "Nintendo Switch", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "L.A. Noire (Nintendo Switch)", "image": "images/uploads/upload-0076.jpg", "category": "Nintendo Switch", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "WRC 10 (Nintendo Switch)", "image": "images/uploads/upload-0077.jpg", "category": "Nintendo Switch", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "WRC 10 (Nintendo Switch)", "image": "images/uploads/upload-0078.jpg", "category": "Nintendo Switch", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Cars 3: Driven to Win (Nintendo Switch)", "image": "images/uploads/upload-0079.jpg", "category": "Nintendo Switch", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Cars 3: Driven to Win (Nintendo Switch)", "image": "images/uploads/upload-0080.jpg", "category": "Nintendo Switch", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Xenoblade Chronicles 2: Torna – The Golden Country (Nintendo Switch)", "image": "images/uploads/upload-0081.jpg", "category": "Nintendo Switch", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Xenoblade Chronicles 2: Torna – The Golden Country (Nintendo Switch)", "image": "images/uploads/upload-0082.jpg", "category": "Nintendo Switch", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Crystal Version (Game Boy Color)", "image": "images/uploads/upload-0083.jpg", "category": "Game Boy Color", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Crystal Version (Game Boy Color)", "image": "images/uploads/upload-0084.jpg", "category": "Game Boy Color", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Tweedehands Game 085", "image": "images/uploads/upload-0085.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon LeafGreen Version (Game Boy Advance)", "image": "images/uploads/upload-0086.jpg", "category": "Game Boy Advance", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon LeafGreen Version (Game Boy Advance)", "image": "images/uploads/upload-0087.jpg", "category": "Game Boy Advance", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Emerald Version (Game Boy Advance)", "image": "images/uploads/upload-0088.jpg", "category": "Game Boy Advance", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Emerald Version (Game Boy Advance)", "image": "images/uploads/upload-0089.jpg", "category": "Game Boy Advance", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Sapphire Version (Game Boy Advance)", "image": "images/uploads/upload-0090.jpg", "category": "Game Boy Advance", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Sapphire Version (Game Boy Advance)", "image": "images/uploads/upload-0091.jpg", "category": "Game Boy Advance", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Y (Nintendo 3DS)", "image": "images/uploads/upload-0092.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon SoulSilver Version (Nintendo DS)", "image": "images/uploads/upload-0093.jpg", "category": "Nintendo DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Tweedehands Game 094", "image": "images/uploads/upload-0094.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Mystery Dungeon: Explorers of Darkness (Nintendo DS)", "image": "images/uploads/upload-0095.jpg", "category": "Nintendo DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon FireRed Version (Game Boy Advance)", "image": "images/uploads/upload-0096.jpg", "category": "Game Boy Advance", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon FireRed Version (Game Boy Advance)", "image": "images/uploads/upload-0097.jpg", "category": "Game Boy Advance", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Mystery Dungeon: Explorers of Sky (Nintendo DS)", "image": "images/uploads/upload-0098.jpg", "category": "Nintendo DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Tweedehands Game 099", "image": "images/uploads/upload-0099.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Super Mystery Dungeon (Nintendo 3DS)", "image": "images/uploads/upload-0100.jpg", "category": "Nintendo 3DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Mystery Dungeon: Blue Rescue Team (Nintendo DS)", "image": "images/uploads/upload-0101.jpg", "category": "Nintendo DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Diamond Version (Nintendo DS)", "image": "images/uploads/upload-0102.jpg", "category": "Nintendo DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Pearl Version (Nintendo DS)", "image": "images/uploads/upload-0103.jpg", "category": "Nintendo DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Mystery Dungeon: Explorers of Time (Nintendo DS)", "image": "images/uploads/upload-0104.jpg", "category": "Nintendo DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Black Version (Nintendo DS)", "image": "images/uploads/upload-0105.jpg", "category": "Nintendo DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon White Version (Nintendo DS)", "image": "images/uploads/upload-0106.jpg", "category": "Nintendo DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Tweedehands Game 107", "image": "images/uploads/upload-0107.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon HeartGold Version (Nintendo DS)", "image": "images/uploads/upload-0108.jpg", "category": "Nintendo DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Pokémon Platinum Version (Nintendo DS)", "image": "images/uploads/upload-0109.jpg", "category": "Nintendo DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "New Nintendo 2DS XL (White/Orange) Console", "image": "images/uploads/upload-0110.jpg", "category": "Nintendo 2DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "New Nintendo 2DS XL (White/Orange) Console", "image": "images/uploads/upload-0111.jpg", "category": "Nintendo 2DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Tweedehands Game 112", "image": "images/uploads/upload-0112.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Tweedehands Game 113", "image": "images/uploads/upload-0113.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "New Nintendo 2DS XL (Black/Turquoise) Console", "image": "images/uploads/upload-0114.jpg", "category": "Nintendo 2DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
//   {"title": "Tweedehands Game 115", "image": "images/uploads/upload-0115.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "New Nintendo 2DS XL (Black/Turquoise) Console", "image": "images/uploads/upload-0116.jpg", "category": "Nintendo 2DS", "price": 0, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 117", "image": "images/uploads/upload-0117.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 118", "image": "images/uploads/upload-0118.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 119", "image": "images/uploads/upload-0119.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 120", "image": "images/uploads/upload-0120.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 121", "image": "images/uploads/upload-0121.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 122", "image": "images/uploads/upload-0122.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 123", "image": "images/uploads/upload-0123.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 124", "image": "images/uploads/upload-0124.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 125", "image": "images/uploads/upload-0125.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 126", "image": "images/uploads/upload-0126.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 127", "image": "images/uploads/upload-0127.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 128", "image": "images/uploads/upload-0128.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 129", "image": "images/uploads/upload-0129.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 130", "image": "images/uploads/upload-0130.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 131", "image": "images/uploads/upload-0131.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 132", "image": "images/uploads/upload-0132.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 133", "image": "images/uploads/upload-0133.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 134", "image": "images/uploads/upload-0134.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 135", "image": "images/uploads/upload-0135.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 136", "image": "images/uploads/upload-0136.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 137", "image": "images/uploads/upload-0137.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 138", "image": "images/uploads/upload-0138.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 139", "image": "images/uploads/upload-0139.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 140", "image": "images/uploads/upload-0140.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 141", "image": "images/uploads/upload-0141.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 142", "image": "images/uploads/upload-0142.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 143", "image": "images/uploads/upload-0143.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 144", "image": "images/uploads/upload-0144.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 145", "image": "images/uploads/upload-0145.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 146", "image": "images/uploads/upload-0146.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 147", "image": "images/uploads/upload-0147.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 148", "image": "images/uploads/upload-0148.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 149", "image": "images/uploads/upload-0149.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 150", "image": "images/uploads/upload-0150.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 151", "image": "images/uploads/upload-0151.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 152", "image": "images/uploads/upload-0152.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 153", "image": "images/uploads/upload-0153.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 154", "image": "images/uploads/upload-0154.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 155", "image": "images/uploads/upload-0155.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 156", "image": "images/uploads/upload-0156.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 157", "image": "images/uploads/upload-0157.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 158", "image": "images/uploads/upload-0158.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 159", "image": "images/uploads/upload-0159.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 160", "image": "images/uploads/upload-0160.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 161", "image": "images/uploads/upload-0161.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 162", "image": "images/uploads/upload-0162.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 163", "image": "images/uploads/upload-0163.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 164", "image": "images/uploads/upload-0164.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 165", "image": "images/uploads/upload-0165.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 166", "image": "images/uploads/upload-0166.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 167", "image": "images/uploads/upload-0167.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 168", "image": "images/uploads/upload-0168.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 169", "image": "images/uploads/upload-0169.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 170", "image": "images/uploads/upload-0170.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 171", "image": "images/uploads/upload-0171.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 172", "image": "images/uploads/upload-0172.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 173", "image": "images/uploads/upload-0173.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 174", "image": "images/uploads/upload-0174.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 175", "image": "images/uploads/upload-0175.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 176", "image": "images/uploads/upload-0176.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 177", "image": "images/uploads/upload-0177.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 178", "image": "images/uploads/upload-0178.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 179", "image": "images/uploads/upload-0179.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 180", "image": "images/uploads/upload-0180.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 181", "image": "images/uploads/upload-0181.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 182", "image": "images/uploads/upload-0182.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 183", "image": "images/uploads/upload-0183.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 184", "image": "images/uploads/upload-0184.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 185", "image": "images/uploads/upload-0185.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 186", "image": "images/uploads/upload-0186.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 187", "image": "images/uploads/upload-0187.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"},
  {"title": "Tweedehands Game 188", "image": "images/uploads/upload-0188.jpg", "category": "Marktplaats", "price": 14.95, "pricing_source": "marktplaats", "item_kind": "game"}
];

UPLOAD_ITEMS.push(
  {"title": "Hokko Life", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Jumanji: The Video Game", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Yooka‑Laylee and the Impossible Lair", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Starlink: Battle for Atlas", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "FIFA 23 Legacy Edition", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Paper Mario: The Origami King", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "1‑2‑Switch", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Sonic Frontiers", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "LEGO Star Wars: The Skywalker Saga", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "The LEGO Ninjago Movie Video Game", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Mario Strikers: Battle League Football", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Mario Kart 8 Deluxe", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Pokkén Tournament DX", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Pokémon Legends: Arceus", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "The Legend of Zelda: Breath of the Wild", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Story of Seasons: Pioneers of Olive Town", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Monster Hunter Rise", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "The Legend of Zelda: Tears of the Kingdom", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "PAW Patrol: On a Roll!", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Legend of Kay Anniversary", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Chocobo GP", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Dragon Quest Treasures", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "LEGO Marvel Super Heroes 2", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Just Dance 2020", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "LEGO DC Super‑Villains", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "EA Sports FC 24", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Hello Neighbor", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Dragon Ball Xenoverse 2", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "FIFA 21 Legacy Edition", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Just Dance 2018", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Carnival Games", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Disgaea 4 Complete+", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Slide Stars", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Five Nights at Freddy’s: Help Wanted", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Super Kickers League Ultimate", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Poi: Explorer Edition", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "South Park: The Fractured but Whole", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Five Nights at Freddy’s: Core Collection", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Tomb Raider I–II–III Remastered", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Monster Jam Steel Titans 2", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Farming Simulator 23: Nintendo Switch Edition", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "VOEZ", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Captain Toad: Treasure Tracker", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "The Unicorn Princess", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Mario Strikers: Battle League Football", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Super Mario RPG", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Asterix & Obelix XXL 2", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Disney Illusion Island", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Plants vs. Zombies: Battle for Neighborville – Complete Edition", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Pokémon: Let’s Go, Eevee!", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Just Dance 2022", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Hot Wheels Unleashed", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Super Mario Maker 2", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Just Dance 2019", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "RollerCoaster Tycoon Adventures", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Mario & Sonic op de Olympische Spelen – Tokyo 2020", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Batman: The Telltale Series", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Hot Wheels Unleashed", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Mijn Paarden Wereld 2: een nieuw avontuur", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "FIFA 22 Legacy Edition", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Kao the Kangaroo", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "FIFA 19", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Just Dance 2021", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Animal Crossing: New Horizons", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Gear Club Unlimited 2", "image": "", "category": "Nintendo Switch", "price": 0, "pricing_source": "manual", "item_kind": "game"}
);
