// This file adds Wii and Wii U products with price 0 to the UPLOAD_ITEMS array.
// Each entry references a placeholder image. Replace the image paths with actual product images as needed.
window.UPLOAD_ITEMS = (window.UPLOAD_ITEMS || []).concat([
  {"title": "Angry Birds Trilogy", "image": "images/products/wii/angry_birds_trilogy.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Wii Sports Resort", "image": "images/products/wii/wii_sports_resort.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "LEGO Harry Potter: Years 1–4", "image": "images/products/wii/lego_harry_potter_years_1_4.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "LEGO Harry Potter: Years 5–7", "image": "images/products/wii/lego_harry_potter_years_5_7.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "LEGO Star Wars III: The Clone Wars", "image": "images/products/wii/lego_star_wars_iii_the_clone_wars.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Rayman Origins", "image": "images/products/wii/rayman_origins.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Super Mario 3D World", "image": "images/products/wiiu/super_mario_3d_world.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Mario & Sonic at the Olympic Winter Games Vancouver 2010", "image": "images/products/wii/mario_sonic_olympics_vancouver_2010.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Mario Party 9", "image": "images/products/wii/mario_party_9.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Donkey Kong Country Returns", "image": "images/products/wii/donkey_kong_country_returns_selects.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game", "edition": "Nintendo Selects"},
  {"title": "Super Mario Galaxy", "image": "images/products/wii/super_mario_galaxy.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Mario Party 8", "image": "images/products/wii/mario_party_8_selects.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game", "edition": "Nintendo Selects"},
  {"title": "PokéPark Wii: Pikachu’s Adventure", "image": "images/products/wii/pokepark_wii_pikachus_adventure.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Wii Party", "image": "images/products/wii/wii_party_selects.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game", "edition": "Nintendo Selects"},
  {"title": "Donkey Kong Country Returns", "image": "images/products/wii/donkey_kong_country_returns.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Super Mario Galaxy 2", "image": "images/products/wii/super_mario_galaxy_2.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Minecraft Wii U Edition", "image": "images/products/wiiu/minecraft_wiiu_edition.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Yoshi’s Woolly World", "image": "images/products/wiiu/yoshis_woolly_world.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "New Super Luigi U", "image": "images/products/wiiu/new_super_luigi_u.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Super Mario Maker", "image": "images/products/wiiu/super_mario_maker.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Kirby and the Rainbow Paintbrush", "image": "images/products/wiiu/kirby_and_the_rainbow_paintbrush.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Just Dance 2019", "image": "images/products/wiiu/just_dance_2019.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Super Smash Bros. for Wii U", "image": "images/products/wiiu/super_smash_bros_wii_u.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "LEGO Star Wars: The Force Awakens", "image": "images/products/wiiu/lego_star_wars_the_force_awakens.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "The Legend of Zelda: Twilight Princess", "image": "images/products/wii/the_legend_of_zelda_twilight_princess.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Captain Toad: Treasure Tracker", "image": "images/products/wiiu/captain_toad_treasure_tracker_selects.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game", "edition": "Nintendo Selects"},
  {"title": "Mario Party 10", "image": "images/products/wiiu/mario_party_10.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "The Legend of Zelda: The Wind Waker HD", "image": "images/products/wiiu/the_legend_of_zelda_wind_waker_hd_selects.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game", "edition": "Nintendo Selects"},
  {"title": "Planes", "image": "images/products/wiiu/planes.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "The Legend of Zelda: Breath of the Wild", "image": "images/products/wiiu/the_legend_of_zelda_breath_of_the_wild.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "LEGO Dimensions", "image": "images/products/wiiu/lego_dimensions.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Splatoon", "image": "images/products/wiiu/splatoon.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Mario & Sonic at the Olympic Winter Games Sochi 2014", "image": "images/products/wiiu/mario_sonic_olympics_sochi_2014.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Just Dance 2018", "image": "images/products/wiiu/just_dance_2018.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "LEGO Jurassic World", "image": "images/products/wiiu/lego_jurassic_world.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Pokkén Tournament", "image": "images/products/wiiu/pokken_tournament.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Wii Party U", "image": "images/products/wiiu/wii_party_u.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Sonic Lost World: Deadly Six Edition", "image": "images/products/wiiu/sonic_lost_world_deadly_six_edition.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "New Super Mario Bros. Wii", "image": "images/products/wii/new_super_mario_bros_wii.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Monopoly", "image": "images/products/wii/monopoly.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Dragon Ball: Revenge of King Piccolo", "image": "images/products/wii/dragon_ball_revenge_of_king_piccolo.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Super Smash Bros. Brawl", "image": "images/products/wii/super_smash_bros_brawl.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "LEGO Indiana Jones: The Original Adventures", "image": "images/products/wii/lego_indiana_jones_the_original_adventures.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Need for Speed: Most Wanted U", "image": "images/products/wiiu/need_for_speed_most_wanted_u.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "LEGO Marvel Super Heroes", "image": "images/products/wiiu/lego_marvel_super_heroes.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Wario Land: The Shake Dimension", "image": "images/products/wii/wario_land_the_shake_dimension.jpg", "category": "Wii", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "The Legend of Zelda: Twilight Princess HD", "image": "images/products/wiiu/the_legend_of_zelda_twilight_princess_hd.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"},
  {"title": "Just Dance 2017", "image": "images/products/wiiu/just_dance_2017.jpg", "category": "Wii U", "price": 0, "pricing_source": "manual", "item_kind": "game"}
]);